# User-db deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-database
  template:
    metadata:
      labels:
        app: user-database
        tier: backend
    spec:
      containers:
        - name: user-dbdatabase
          image: postgres:13
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: all-credentials
                  key: USER_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: all-credentials
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: all-credentials
                  key: DB_PASSWORD

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-database-volume-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: user-database-volume-mount
          persistentVolumeClaim:
            claimName: user-database-pvc



---

# User-db service

apiVersion: v1
kind: Service
metadata:
  name: user-database-service
spec:
  selector:
    app: user-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP



---


# User-db volume claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
