# api-db deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
        tier: backend
    spec:
      containers:
        - name: api-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: all-credentials
                  key: APIGATEWAY_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: all-credentials
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: all-credentials
                  key: DB_PASSWORD
                
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: api-db-volume-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: api-db-volume-mount
          persistentVolumeClaim:
            claimName: api-db-pvc
      restartPolicy: Always


---

# api-db service

apiVersion: v1
kind: Service
metadata:
  name: api-db-service
spec:
  selector:
    app: api-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP


---

# api-db volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/api-db-pv


---

# api-db volume claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-db-pvc
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: api-db-pv
